/** Copy for the desk homepage, written in Tobias's voice. */
export const deskCopy = {
  fr: {
    hint: "Attrapez les objets. Cliquez pour ouvrir.",
    sheetLabel: "Tobias Ringot · Aix-en-Provence",
    title1: "Des sites qui vendent.",
    title2: "Des logiciels qui bossent.",
    lead: "Je dessine, je code et je livre moi-même. Un seul interlocuteur, des prix écrits noir sur blanc, et des outils que vos équipes ont envie d'ouvrir le matin.",
    ctaQuote: "Estimer mon site",
    ctaCall: "Être rappelé",
    postitAvailable: "Dispo pour 2 nouveaux projets ce trimestre ✓",
    postitCoffee: "Café offert au premier rendez-vous.",
    phoneLabel: "Me rappeler",
    phoneNote: "Sans engagement",
    folderLabel: "Réalisations",
    folderNote: "7 projets dedans",
    quoteLabel: "Devis n° 2026-09",
    quoteLine: "Refonte de site",
    quotePrice: "dès 1 800 €",
    stamp: "Ouvert",
    trustLabel: "Ils bossent avec moi",
    painsLabel: "Ce qui traîne sur votre bureau",
    pains: [
      "Le site date de 2014 et personne n'a les accès.",
      "Les devis se font sur devis_v12_FINAL_ok.xlsx",
      "Le stock est dans la tête de Michel.",
      "On ressaisit la même commande trois fois.",
      "Le logiciel du marché : 40 €/mois/personne pour 3 boutons.",
      "Le stagiaire est parti avec le mot de passe Wix.",
    ],
    painsTitle: "On range tout ça.",
    painsText: "Un site qui fait venir des clients, un logiciel qui fait exactement ce dont vous avez besoin. Rien de plus, rien de moins, et c'est à vous.",
    painsCta: "Parler de mon projet",
    offersLabel: "Devis",
    offersTitle: "Les prix, écrits noir sur blanc.",
    offersClient: "Client : vous",
    offersDate: "Valable : toute l'année",
    offersTotal: "Total surprises",
    offersZero: "0,00 €",
    offersSign: "Signé : Tobias",
    offersNote: "Prix HT indicatifs. Le prix final est fixé dans un devis détaillé, ligne par ligne.",
    projectsLabel: "Chemise « Réalisations »",
    projectsTitle: "Des projets faits pour leur métier.",
    projectsText: "Logiciel de gestion pour le bâtiment, immobilier de prestige, architecture, travaux publics, restaurant, vin. Chaque projet part du terrain du client.",
    projectsAll: "Ouvrir toute la chemise",
    visit: "Voir le site",
    methodLabel: "Check-list",
    methodTitle: "Comment ça se passe",
    guaranteesLabel: "Ticket de caisse",
    guaranteesTitle: "Vous savez ce que vous achetez.",
    receiptLines: [
      ["Garantie après mise en ligne", "3 mois"],
      ["Réponse maximum", "24 h"],
      ["Code & données à vous", "100 %"],
      ["Engagement avant devis", "0 €"],
    ],
    receiptPay: "Paiement en 3 fois : 30 / 40 / 30 %",
    receiptThanks: "Merci, à bientôt sur le chantier.",
    aboutLabel: "Cadre photo",
    aboutTitle: "Moi, c'est Tobias.",
    aboutText:
      "Je viens de la vente, puis du design produit, et j'ai fini par coder ce que je dessinais. Aujourd'hui je construis le logiciel de gestion d'une entreprise du bâtiment et les sites de commerçants, architectes et artisans entre Aix et Marseille. Je comprends votre métier avant de toucher à l'écran.",
    aboutNote: "← photo prise un soir de chantier, une vraie arrive",
    aboutCta: "Lire la suite",
    faqLabel: "Fiches",
    faqTitle: "Les questions qu'on me pose",
    contactLabel: "Téléphone",
    contactTitle: "On en parle ?",
    contactText: "Décrivez votre activité et votre besoin en trois lignes, ou laissez un numéro : je rappelle moi-même.",
    contactEmail: "Écrire directement",
    footerTag: "Fabriqué à Aix-en-Provence, sur ce bureau.",
  },
  en: {
    hint: "Grab the objects. Click to open.",
    sheetLabel: "Tobias Ringot · Aix-en-Provence",
    title1: "Websites that sell.",
    title2: "Software that works.",
    lead: "I design, code and ship everything myself. One point of contact, prices in writing, and tools your team actually wants to open in the morning.",
    ctaQuote: "Estimate my website",
    ctaCall: "Request a call",
    postitAvailable: "Room for 2 new projects this quarter ✓",
    postitCoffee: "Coffee's on me at the first meeting.",
    phoneLabel: "Call me back",
    phoneNote: "No commitment",
    folderLabel: "Work",
    folderNote: "7 projects inside",
    quoteLabel: "Quote no. 2026-09",
    quoteLine: "Website redesign",
    quotePrice: "from €1,800",
    stamp: "Open",
    trustLabel: "They work with me",
    painsLabel: "What's piling up on your desk",
    pains: [
      "The website is from 2014 and nobody has the login.",
      "Quotes live in quote_v12_FINAL_ok.xlsx",
      "Stock levels live in Michael's head.",
      "The same order gets typed in three times.",
      "Off-the-shelf software: €40/month/user for 3 buttons.",
      "The intern left with the Wix password.",
    ],
    painsTitle: "Let's tidy this up.",
    painsText: "A website that brings clients in, software that does exactly what you need. Nothing more, nothing less, and it's yours.",
    painsCta: "Talk about my project",
    offersLabel: "Quote",
    offersTitle: "Prices, in black and white.",
    offersClient: "Client: you",
    offersDate: "Valid: all year",
    offersTotal: "Total surprises",
    offersZero: "€0.00",
    offersSign: "Signed: Tobias",
    offersNote: "Indicative prices excl. VAT. The final price is set in a detailed, line-by-line quote.",
    projectsLabel: "“Work” folder",
    projectsTitle: "Projects built for their trade.",
    projectsText: "Management software for construction, luxury real estate, architecture, public works, a restaurant, a winery. Every project starts from the client's day-to-day.",
    projectsAll: "Open the whole folder",
    visit: "Visit site",
    methodLabel: "Checklist",
    methodTitle: "How it goes",
    guaranteesLabel: "Receipt",
    guaranteesTitle: "You know what you're buying.",
    receiptLines: [
      ["Warranty after launch", "3 months"],
      ["Maximum response time", "24 h"],
      ["Code & data yours", "100 %"],
      ["Commitment before quote", "€0"],
    ],
    receiptPay: "Paid in 3 instalments: 30 / 40 / 30 %",
    receiptThanks: "Thanks, see you on site.",
    aboutLabel: "Photo frame",
    aboutTitle: "I'm Tobias.",
    aboutText:
      "I started in sales, moved to product design, and ended up coding what I was drawing. Today I build the management software of a construction company and the websites of shops, architects and trades between Aix and Marseille. I understand your trade before I touch the screen.",
    aboutNote: "← taken one evening on site, a proper one is coming",
    aboutCta: "Read more",
    faqLabel: "Cards",
    faqTitle: "Questions I get asked",
    contactLabel: "Phone",
    contactTitle: "Shall we talk?",
    contactText: "Describe your business and your need in three lines, or leave a number: I call back myself.",
    contactEmail: "Email me directly",
    footerTag: "Made in Aix-en-Provence, on this desk.",
  },
} as const;
