import type { Locale } from "@/lib/i18n";

export const salesCopy = {
  fr: {
    heroKicker: "Refonte & création de sites vitrines",
    heroNote: "Pour les écoles, commerces et professionnels de l'immobilier qui veulent un site à la hauteur de leur activité.",
    servicesHeading: "Votre site peut faire mieux.",
    servicesDescription: "Un site vieillissant peut freiner la confiance. Je clarifie votre offre, soigne l'expérience et construis un site que vos prospects ont envie de parcourir.",
    services: [
      { title: "Refonte de site", tag: "Cœur de l'offre", description: "Moderniser un site existant, simplifier son parcours et redonner de la force à votre message." },
      { title: "Site vitrine", tag: "Cœur de l'offre", description: "Présenter clairement votre activité avec un site sur mesure, rapide et facile à consulter." },
      { title: "Landing page", tag: "Offre ciblée", description: "Une page dédiée à une offre, pensée pour guider les visiteurs vers une prise de contact." },
      { title: "Maintenance", tag: "Après la mise en ligne", description: "Garder votre site à jour et l'accompagner dans la durée selon vos besoins." },
    ],
    servicesCta: "Parler de mon site",
    projectsHeading: "Quelques sites à découvrir",
    projectsDescription: "Deux projets en ligne à explorer. Les études de cas détaillées seront ajoutées progressivement.",
    projectsPageHeading: "Projets sélectionnés",
    projectsPageDescription: "Des sites concrets, à parcourir directement. D'autres projets arriveront bientôt.",
    projects: [
      { title: "Parentez²", category: "Architecture intérieure · Site vitrine", description: "Un site pour présenter un studio d'architecture intérieure, ses projets et sa vision.", imageAlt: "Aperçu du site Parentez²" },
      { title: "Mistral TP", category: "Travaux publics · Site vitrine", description: "Un site qui présente les métiers, la méthode et les réalisations d'une entreprise de travaux publics.", imageAlt: "Aperçu du site Mistral TP" },
    ],
    visitProject: "Voir le site",
    placeholderTitle: "Votre prochain projet ici",
    placeholderCategory: "Projet à venir",
    placeholderDescription: "Lorem ipsum — emplacement réservé pour une prochaine réalisation.",
    approachHeading: "Un projet clair, du premier échange à la mise en ligne.",
    approachSteps: [
      { title: "Comprendre", description: "On fait le point sur votre activité, votre site actuel et ce que vous attendez du nouveau." },
      { title: "Concevoir", description: "Je structure les contenus et crée une direction visuelle cohérente avec votre marque." },
      { title: "Mettre en ligne", description: "Je développe le site, vérifie son rendu sur chaque écran et vous accompagne au lancement." },
    ],
    testimonialHeading: "Ils en parleront mieux que moi",
    testimonialNote: "Exemples de mise en page — témoignages fictifs à remplacer avant publication.",
    testimonialExamples: [
      "Exemple de témoignage client : notre nouveau site présente enfin clairement notre activité et facilite les prises de contact.",
      "Exemple de témoignage client : Tobias a su transformer nos idées en une expérience simple et fidèle à notre marque.",
    ],
    formHeading: "Parlez-moi de votre projet",
    formDescription: "Quelques lignes suffisent pour démarrer. Décrivez votre site actuel et ce que vous souhaitez améliorer.",
    formName: "Votre nom",
    formEmail: "Votre e-mail",
    formCompany: "Entreprise / activité",
    formWebsite: "Site actuel (facultatif)",
    formService: "Votre besoin",
    formServicePlaceholder: "Choisir un service",
    formMessage: "Votre projet en quelques mots",
    formSend: "Envoyer ma demande",
    formSending: "Envoi en cours…",
    formSuccess: "Merci ! Votre message a bien été envoyé.",
    formError: "L'envoi n'a pas abouti. Vous pouvez aussi m'écrire directement par e-mail.",
    formPrivacy: "Vos informations servent uniquement à vous répondre.",
    directEmail: "Écrire directement",
  },
  en: {
    heroKicker: "Website redesign & showcase sites",
    heroNote: "For schools, local businesses and independent real-estate professionals ready for a better website.",
    servicesHeading: "Your website can do more.",
    servicesDescription: "An outdated site can weaken trust. I clarify your offer, improve the experience and build a site people want to explore.",
    services: [
      { title: "Website redesign", tag: "Core service", description: "Modernize an existing site, simplify its journey and sharpen your message." },
      { title: "Showcase website", tag: "Core service", description: "Present your business clearly with a tailored, fast and easy-to-use website." },
      { title: "Landing page", tag: "Focused offer", description: "A dedicated page that guides visitors from an offer to an enquiry." },
      { title: "Maintenance", tag: "After launch", description: "Keep your site current and supported as your business evolves." },
    ],
    servicesCta: "Tell me about your site",
    projectsHeading: "A few sites to explore",
    projectsDescription: "Two live projects you can browse. Detailed case studies will be added over time.",
    projectsPageHeading: "Selected projects",
    projectsPageDescription: "Real websites, ready to explore. More projects are coming soon.",
    projects: [
      { title: "Parentez²", category: "Interior architecture · Showcase site", description: "A site presenting an interior architecture studio, its projects and its vision.", imageAlt: "Preview of the Parentez² website" },
      { title: "Mistral TP", category: "Public works · Showcase site", description: "A site presenting the services, approach and work of a public works company.", imageAlt: "Preview of the Mistral TP website" },
    ],
    visitProject: "Visit website",
    placeholderTitle: "Your next project here",
    placeholderCategory: "Coming soon",
    placeholderDescription: "Lorem ipsum — space reserved for another project.",
    approachHeading: "A clear process, from first conversation to launch.",
    approachSteps: [
      { title: "Understand", description: "We discuss your business, your current website and what the new one needs to achieve." },
      { title: "Design", description: "I organize the content and create a visual direction aligned with your brand." },
      { title: "Launch", description: "I build the site, check it across screens and support you through launch." },
    ],
    testimonialHeading: "Their words will speak louder",
    testimonialNote: "Layout examples — fictional testimonials to replace before publishing.",
    testimonialExamples: [
      "Sample client quote: our new website finally explains our business and makes it easier to get in touch.",
      "Sample client quote: Tobias turned our ideas into a simple experience that feels true to our brand.",
    ],
    formHeading: "Tell me about your project",
    formDescription: "A few lines are enough to start. Tell me about your current site and what you want to improve.",
    formName: "Your name",
    formEmail: "Your email",
    formCompany: "Business / activity",
    formWebsite: "Current website (optional)",
    formService: "What do you need?",
    formServicePlaceholder: "Choose a service",
    formMessage: "Your project in a few words",
    formSend: "Send my enquiry",
    formSending: "Sending…",
    formSuccess: "Thank you! Your message has been sent.",
    formError: "The message could not be sent. You can also email me directly.",
    formPrivacy: "Your information is used only to reply to you.",
    directEmail: "Email me directly",
  },
  zh: {
    heroKicker: "网站改版与企业展示网站",
    heroNote: "面向希望升级网站的学校、商家和独立房地产从业者。",
    servicesHeading: "让您的网站发挥更大作用。",
    servicesDescription: "老旧的网站可能影响信任。我帮助您理清业务、优化体验，打造值得浏览的网站。",
    services: [
      { title: "网站改版", tag: "核心服务", description: "更新现有网站，简化浏览路径，让信息更有说服力。" },
      { title: "企业展示网站", tag: "核心服务", description: "用快速、易用的定制网站清晰展示您的业务。" },
      { title: "落地页", tag: "专项服务", description: "为单一服务打造页面，引导访客主动联系。" },
      { title: "网站维护", tag: "上线之后", description: "根据需要持续更新和维护网站。" },
    ],
    servicesCta: "聊聊我的网站",
    projectsHeading: "近期网站项目",
    projectsDescription: "欢迎浏览两个已上线的项目。详细案例将陆续补充。",
    projectsPageHeading: "精选项目",
    projectsPageDescription: "可以直接浏览的真实网站。更多项目即将上线。",
    projects: [
      { title: "Parentez²", category: "室内建筑 · 展示网站", description: "展示室内建筑工作室、项目与理念的网站。", imageAlt: "Parentez² 网站预览" },
      { title: "Mistral TP", category: "公共工程 · 展示网站", description: "介绍一家公共工程公司的服务、方法与项目的网站。", imageAlt: "Mistral TP 网站预览" },
    ],
    visitProject: "访问网站",
    placeholderTitle: "下一个项目将在这里",
    placeholderCategory: "即将推出",
    placeholderDescription: "Lorem ipsum — 为未来项目预留的位置。",
    approachHeading: "从第一次沟通到正式上线，过程清晰可见。",
    approachSteps: [
      { title: "了解", description: "了解您的业务、当前网站和新网站的目标。" },
      { title: "设计", description: "组织内容，制定符合品牌的视觉方向。" },
      { title: "上线", description: "开发网站、检查各类屏幕的效果并协助上线。" },
    ],
    testimonialHeading: "未来的客户反馈",
    testimonialNote: "排版示例——虚构评价，上线前必须替换。",
    testimonialExamples: [
      "客户评价示例：新网站终于清楚地介绍了我们的业务，也让客户更容易联系我们。",
      "客户评价示例：Tobias 将我们的想法变成了简单且符合品牌的体验。",
    ],
    formHeading: "介绍您的项目",
    formDescription: "简单介绍当前网站和您想改进的地方，我们就可以开始交流。",
    formName: "您的姓名",
    formEmail: "您的电子邮箱",
    formCompany: "公司 / 业务",
    formWebsite: "当前网站（选填）",
    formService: "您的需求",
    formServicePlaceholder: "选择服务",
    formMessage: "简单介绍项目",
    formSend: "发送咨询",
    formSending: "发送中…",
    formSuccess: "谢谢！您的消息已发送。",
    formError: "消息发送失败。您也可以直接发邮件给我。",
    formPrivacy: "您的信息仅用于回复您的咨询。",
    directEmail: "直接发邮件",
  },
} as const satisfies Record<Locale, object>;
