import type { Locale } from "@/lib/i18n";

export const salesCopy = {
  fr: {
    heroKicker: "Refonte de sites internet · Aix-en-Provence",
    heroNote: "Pour les artisans, industriels, commerces et indépendants de Provence.",
    heroPrice: "Refonte à partir de 1 500 €",
    marqueeLabel: "Aperçu des réalisations",
    servicesEyebrow: "Services",
    servicesHeading: "Un site à la hauteur de votre entreprise.",
    servicesDescription: "Vous connaissez votre métier. Je m'occupe de le rendre clair, rassurant et facile à contacter, sur ordinateur comme sur téléphone.",
    featured: {
      tag: "Offre principale",
      title: "Refonte de site internet",
      description: "Je reprends votre site existant, vos contenus et votre identité pour en faire un site moderne qui donne envie de vous contacter.",
      priceFrom: "À partir de",
      price: "1 500 €",
      priceNote: "Devis précis après un échange de 20 minutes.",
      included: [
        "Nouveau design fidèle à votre marque",
        "Pensé d'abord pour le téléphone",
        "Vos vrais contenus réorganisés et réécrits",
        "Formulaire de contact et appel en un geste",
        "Titres et descriptions pour Google",
        "Vérifié sur Chrome et Safari, puis mis en ligne",
      ],
      cta: "Parler de ma refonte",
    },
    services: [
      { title: "Site vitrine", tag: "À partir de 1 500 €", description: "Vous n'avez pas encore de site : je crée un site sur mesure qui présente clairement votre activité." },
      { title: "Landing page", tag: "Sur devis", description: "Une page dédiée à une offre ou une saison, pensée pour transformer les visiteurs en demandes." },
      { title: "Maintenance", tag: "Sur devis", description: "Mises à jour de contenus, petites évolutions et suivi du site après la mise en ligne." },
    ],
    projectsEyebrow: "Réalisations",
    projectsHeading: "Des sites conçus pour des entreprises de Provence",
    projectsDescription: "Sites vitrines, landing pages et sites sur mesure, du design à la mise en ligne.",
    projectsPageHeading: "Réalisations",
    projectsPageDescription: "Des sites conçus et développés de A à Z, chacun pensé pour son métier.",
    visitProject: "Voir le site",
    allProjects: "Voir toutes les réalisations",
    hoverHint: "Survolez pour faire défiler",
    approachEyebrow: "Méthode",
    approachHeading: "Un projet clair, du premier échange à la mise en ligne.",
    approachSteps: [
      { title: "Échanger", description: "20 minutes en visio pour comprendre votre activité, votre site actuel et ce que vous attendez du nouveau." },
      { title: "Concevoir", description: "Je réorganise vos contenus et crée une maquette fidèle à votre marque, que vous validez avant la suite." },
      { title: "Mettre en ligne", description: "Je développe le site, le vérifie sur ordinateur et téléphone, puis je vous accompagne au lancement." },
    ],
    aboutEyebrow: "Qui suis-je",
    aboutHeading: "Un interlocuteur unique, à Aix-en-Provence.",
    aboutText: "Je suis Tobias Ringot, web designer. Je m'occupe de tout, du design au développement jusqu'à la mise en ligne : vous avez une seule personne à qui parler, du premier appel au lancement.",
    aboutCta: "En savoir plus sur moi",
    faqEyebrow: "Questions fréquentes",
    faqHeading: "Ce qu'on me demande souvent",
    faq: [
      { q: "Combien coûte une refonte ?", a: "Une refonte démarre à 1 500 €. Le prix final dépend du nombre de pages et des fonctionnalités (prise de rendez-vous, catalogue, plusieurs langues). Vous recevez un devis clair après notre premier échange." },
      { q: "Combien de temps faut-il ?", a: "Cela dépend surtout du nombre de pages et de la disponibilité des contenus. On fixe ensemble un calendrier dès le devis, avec une date de mise en ligne." },
      { q: "Est-ce que je garde mes contenus et mon identité ?", a: "Oui. Je pars de vos textes, photos, logo et couleurs, que je réorganise et mets en valeur. La refonte modernise votre image sans la trahir." },
      { q: "Le site m'appartient-il ?", a: "Oui, le site est livré à votre nom. Vous restez propriétaire de vos contenus et de votre nom de domaine." },
      { q: "Et après la mise en ligne ?", a: "Je vous montre comment le site fonctionne et je reste disponible. Si vous le souhaitez, je peux assurer les mises à jour avec la formule maintenance." },
      { q: "Vous travaillez uniquement à Aix-en-Provence ?", a: "Je suis basé à Aix-en-Provence et je travaille avec des entreprises de toute la Provence. Tout peut aussi se faire à distance, en visio." },
    ],
    formHeading: "Parlez-moi de votre projet",
    formDescription: "Quelques lignes suffisent. Indiquez votre site actuel si vous en avez un.",
    formName: "Votre nom",
    formEmail: "Votre e-mail",
    formCompany: "Entreprise / activité",
    formWebsite: "Site actuel (facultatif)",
    formService: "Votre besoin",
    formServicePlaceholder: "Choisir un service",
    formServices: ["Refonte de site", "Site vitrine", "Landing page", "Maintenance"],
    formMessage: "Votre projet en quelques mots",
    formSend: "Envoyer ma demande",
    formSending: "Envoi en cours…",
    formSuccess: "Merci ! Votre message a bien été envoyé. Je vous réponds personnellement.",
    formError: "L'envoi n'a pas abouti. Vous pouvez aussi m'écrire directement par e-mail.",
    formPrivacy: "Vos informations servent uniquement à vous répondre.",
    directEmail: "Écrire directement",
  },
  en: {
    heroKicker: "Website redesign · Aix-en-Provence",
    heroNote: "For trades, industry, shops and independents across Provence.",
    heroPrice: "Redesign from €1,500",
    marqueeLabel: "Work preview",
    servicesEyebrow: "Services",
    servicesHeading: "A website that matches your business.",
    servicesDescription: "You know your trade. I make it clear, reassuring and easy to contact, on desktop and on mobile.",
    featured: {
      tag: "Main service",
      title: "Website redesign",
      description: "I take your existing site, content and identity and turn them into a modern website that makes people want to get in touch.",
      priceFrom: "From",
      price: "€1,500",
      priceNote: "Detailed quote after a 20-minute call.",
      included: [
        "New design true to your brand",
        "Mobile-first",
        "Your real content reorganised and rewritten",
        "Contact form and one-tap call",
        "Titles and descriptions for Google",
        "Tested on Chrome and Safari, then launched",
      ],
      cta: "Talk about my redesign",
    },
    services: [
      { title: "Showcase website", tag: "From €1,500", description: "No website yet: I create a tailored site that presents your business clearly." },
      { title: "Landing page", tag: "On quote", description: "A page dedicated to one offer or season, built to turn visitors into enquiries." },
      { title: "Maintenance", tag: "On quote", description: "Content updates, small improvements and follow-up after launch." },
    ],
    projectsEyebrow: "Work",
    projectsHeading: "Websites designed for businesses in Provence",
    projectsDescription: "Showcase websites, landing pages and custom sites, from design to launch.",
    projectsPageHeading: "Work",
    projectsPageDescription: "Websites designed and built end to end, each one shaped around its trade.",
    visitProject: "Visit website",
    allProjects: "See all work",
    hoverHint: "Hover to scroll",
    approachEyebrow: "Process",
    approachHeading: "A clear process, from first conversation to launch.",
    approachSteps: [
      { title: "Talk", description: "A 20-minute video call to understand your business, your current site and what the new one needs to do." },
      { title: "Design", description: "I reorganise your content and create a mockup true to your brand, which you approve before we continue." },
      { title: "Launch", description: "I build the site, test it on desktop and mobile, then support you through launch." },
    ],
    aboutEyebrow: "About",
    aboutHeading: "One point of contact, in Aix-en-Provence.",
    aboutText: "I'm Tobias Ringot, web designer. I handle everything from design to development and launch, so you only ever talk to one person.",
    aboutCta: "More about me",
    faqEyebrow: "FAQ",
    faqHeading: "Questions I often get",
    faq: [
      { q: "How much does a redesign cost?", a: "A redesign starts at €1,500. The final price depends on the number of pages and features (booking, catalogue, several languages). You get a clear quote after our first call." },
      { q: "How long does it take?", a: "It mostly depends on the number of pages and when the content is ready. We set a schedule together in the quote, with a launch date." },
      { q: "Do I keep my content and identity?", a: "Yes. I start from your texts, photos, logo and colours, then reorganise and enhance them. The redesign modernises your image without losing it." },
      { q: "Do I own the website?", a: "Yes, the website is delivered in your name. You keep ownership of your content and your domain name." },
      { q: "What happens after launch?", a: "I show you how the site works and stay available. If you wish, I can handle updates through the maintenance plan." },
      { q: "Do you only work in Aix-en-Provence?", a: "I'm based in Aix-en-Provence and work with businesses across Provence. Everything can also be done remotely over video." },
    ],
    formHeading: "Tell me about your project",
    formDescription: "A few lines are enough. Add your current website if you have one.",
    formName: "Your name",
    formEmail: "Your email",
    formCompany: "Business / activity",
    formWebsite: "Current website (optional)",
    formService: "What do you need?",
    formServicePlaceholder: "Choose a service",
    formServices: ["Website redesign", "Showcase website", "Landing page", "Maintenance"],
    formMessage: "Your project in a few words",
    formSend: "Send my enquiry",
    formSending: "Sending…",
    formSuccess: "Thank you! Your message has been sent. I'll reply personally.",
    formError: "The message could not be sent. You can also email me directly.",
    formPrivacy: "Your information is used only to reply to you.",
    directEmail: "Email me directly",
  },
} as const satisfies Record<Locale, object>;
