import type { Locale } from "@/lib/i18n";

export const salesCopy = {
  fr: {
    heroKicker: "Refonte de sites internet · Aix-en-Provence",
    heroNote: "Pour les artisans, industriels, commerces et indépendants de Provence.",
    heroPrice: "Refonte à partir de 1 490 €",
    marqueeLabel: "Aperçu des réalisations",
    servicesEyebrow: "Services",
    servicesHeading: "Un site à la hauteur de votre entreprise.",
    servicesDescription: "Vous connaissez votre métier. Je m'occupe de le rendre clair, rassurant et facile à contacter, sur ordinateur comme sur téléphone.",
    featured: {
      tag: "Offre principale",
      title: "Refonte de site internet",
      description: "Je reprends votre site existant, vos contenus et votre identité pour en faire un site moderne qui donne envie de vous contacter.",
      priceFrom: "À partir de",
      price: "1 490 €",
      priceNote: "Estimation immédiate en ligne, devis détaillé par e-mail.",
      included: [
        "Nouveau design fidèle à votre marque",
        "Pensé d'abord pour le téléphone",
        "Vos vrais contenus réorganisés et réécrits",
        "Formulaire de contact et appel en un geste",
        "Titres et descriptions pour Google",
        "Vérifié sur Chrome et Safari, puis mis en ligne",
      ],
      cta: "Parler de ma refonte",
    },
    services: [
      { title: "Site vitrine", tag: "À partir de 1 490 €", description: "Vous n'avez pas encore de site : je crée un site sur mesure qui présente clairement votre activité." },
      { title: "Landing page", tag: "À partir de 1 090 €", description: "Une page dédiée à une offre ou une saison, pensée pour transformer les visiteurs en demandes." },
      { title: "Maintenance", tag: "Sur devis", description: "Mises à jour de contenus, petites évolutions et suivi du site après la mise en ligne." },
    ],
    projectsEyebrow: "Réalisations",
    projectsHeading: "Des sites qui donnent envie de pousser la porte",
    projectsDescription: "Restaurant, domaine viticole, architecture, travaux publics : chaque site est pensé pour son métier. Survolez une capture pour la faire défiler.",
    projectsPageHeading: "Réalisations",
    projectsPageDescription: "Des sites conçus et développés de A à Z, chacun pensé pour son métier.",
    visitProject: "Visiter le site",
    previewOnRequest: "Site de démonstration, aperçu envoyé sur demande par e-mail.",
    allProjects: "Voir toutes les réalisations",
    hoverHint: "Survolez pour faire défiler",
    approachEyebrow: "Méthode",
    approachHeading: "Un projet clair, du premier message à la mise en ligne.",
    approachSteps: [
      { title: "Comprendre", description: "Vous décrivez votre projet via le formulaire de devis. Je vous envoie par e-mail mes questions et une proposition détaillée." },
      { title: "Concevoir", description: "Je réorganise vos contenus et crée une maquette fidèle à votre marque, que vous validez avant la suite." },
      { title: "Mettre en ligne", description: "Je développe le site, le vérifie sur ordinateur et téléphone, puis je vous accompagne au lancement." },
    ],
    aboutEyebrow: "Qui suis-je",
    aboutHeading: "Un interlocuteur unique, à Aix-en-Provence.",
    aboutText: "Je suis Tobias Ringot, web designer. Je m'occupe de tout, du design au développement jusqu'à la mise en ligne : vous avez une seule personne à qui parler, du premier message au lancement.",
    aboutCta: "En savoir plus sur moi",
    faqEyebrow: "Questions fréquentes",
    faqHeading: "Ce qu'on me demande souvent",
    faq: [
      { q: "Combien coûte une refonte ?", a: "Une refonte démarre à 1 490 €. Le prix final dépend du nombre de pages et des fonctionnalités (prise de rendez-vous, catalogue, plusieurs langues). Le formulaire de devis vous donne une estimation immédiate, puis je vous envoie un devis détaillé par e-mail." },
      { q: "Combien de temps faut-il ?", a: "Cela dépend surtout du nombre de pages et de la disponibilité des contenus. On fixe ensemble un calendrier dès le devis, avec une date de mise en ligne." },
      { q: "Est-ce que je garde mes contenus et mon identité ?", a: "Oui. Je pars de vos textes, photos, logo et couleurs, que je réorganise et mets en valeur. La refonte modernise votre image sans la trahir." },
      { q: "Le site m'appartient-il ?", a: "Oui, le site est livré à votre nom. Vous restez propriétaire de vos contenus et de votre nom de domaine." },
      { q: "Et après la mise en ligne ?", a: "Je vous montre comment le site fonctionne et je reste disponible. Si vous le souhaitez, je peux assurer les mises à jour avec la formule maintenance." },
      { q: "Vous travaillez uniquement à Aix-en-Provence ?", a: "Je suis basé à Aix-en-Provence et je travaille avec des entreprises de toute la Provence. Tout se fait à distance, par e-mail." },
    ],
    quoteCardTag: "Recommandé",
    quoteCardTitle: "Estimer le prix de mon site",
    quoteCardText: "Quelques questions sur votre projet, et une estimation de prix à la fin. Je vous envoie ensuite le devis détaillé par e-mail.",
    quoteCardMeta: ["3 minutes", "Sans engagement", "Devis détaillé par e-mail"],
    quoteCardCta: "Commencer ma demande",
    formHeading: "Plutôt un message rapide ?",
    formDescription: "Quelques lignes suffisent. Indiquez votre site actuel si vous en avez un.",
    formName: "Votre nom",
    formEmail: "Votre e-mail",
    formCompany: "Entreprise / activité",
    formWebsite: "Site actuel (facultatif)",
    formService: "Votre besoin",
    formServicePlaceholder: "Choisir un service",
    formServices: ["Refonte de site", "Site vitrine", "Landing page", "Maintenance"],
    formMessage: "Votre projet en quelques mots",
    formSend: "Envoyer ma demande",
    formSending: "Envoi en cours…",
    formSuccess: "Merci ! Votre message a bien été envoyé. Je vous réponds personnellement.",
    formError: "L'envoi n'a pas abouti. Vous pouvez aussi m'écrire directement par e-mail.",
    formPrivacy: "Vos informations servent uniquement à vous répondre.",
    directEmail: "Écrire directement",
  },
  en: {
    heroKicker: "Website redesign · Aix-en-Provence",
    heroNote: "For trades, industry, shops and independents across Provence.",
    heroPrice: "Redesign from €1,490",
    marqueeLabel: "Work preview",
    servicesEyebrow: "Services",
    servicesHeading: "A website that matches your business.",
    servicesDescription: "You know your trade. I make it clear, reassuring and easy to contact, on desktop and on mobile.",
    featured: {
      tag: "Main service",
      title: "Website redesign",
      description: "I take your existing site, content and identity and turn them into a modern website that makes people want to get in touch.",
      priceFrom: "From",
      price: "€1,490",
      priceNote: "Instant online estimate, detailed quote by email.",
      included: [
        "New design true to your brand",
        "Mobile-first",
        "Your real content reorganised and rewritten",
        "Contact form and one-tap call",
        "Titles and descriptions for Google",
        "Tested on Chrome and Safari, then launched",
      ],
      cta: "Talk about my redesign",
    },
    services: [
      { title: "Showcase website", tag: "From €1,490", description: "No website yet: I create a tailored site that presents your business clearly." },
      { title: "Landing page", tag: "From €1,090", description: "A page dedicated to one offer or season, built to turn visitors into enquiries." },
      { title: "Maintenance", tag: "On quote", description: "Content updates, small improvements and follow-up after launch." },
    ],
    projectsEyebrow: "Work",
    projectsHeading: "Websites that make people want to walk in",
    projectsDescription: "Restaurant, wine estate, architecture, public works: each site is shaped around its trade. Hover a screenshot to scroll through it.",
    projectsPageHeading: "Work",
    projectsPageDescription: "Websites designed and built end to end, each one shaped around its trade.",
    visitProject: "Visit website",
    previewOnRequest: "Demo website, preview available on request by email.",
    allProjects: "See all work",
    hoverHint: "Hover to scroll",
    approachEyebrow: "Process",
    approachHeading: "A clear process, from first conversation to launch.",
    approachSteps: [
      { title: "Understand", description: "You describe your project through the quote form. I email you my questions and a detailed proposal." },
      { title: "Design", description: "I reorganise your content and create a mockup true to your brand, which you approve before we continue." },
      { title: "Launch", description: "I build the site, test it on desktop and mobile, then support you through launch." },
    ],
    aboutEyebrow: "About",
    aboutHeading: "One point of contact, in Aix-en-Provence.",
    aboutText: "I'm Tobias Ringot, web designer. I handle everything from design to development and launch, so you only ever deal with one person.",
    aboutCta: "More about me",
    faqEyebrow: "FAQ",
    faqHeading: "Questions I often get",
    faq: [
      { q: "How much does a redesign cost?", a: "A redesign starts at €1,490. The final price depends on the number of pages and features (booking, catalogue, several languages). The quote form gives you an instant estimate, then I email you a detailed quote." },
      { q: "How long does it take?", a: "It mostly depends on the number of pages and when the content is ready. We set a schedule together in the quote, with a launch date." },
      { q: "Do I keep my content and identity?", a: "Yes. I start from your texts, photos, logo and colours, then reorganise and enhance them. The redesign modernises your image without losing it." },
      { q: "Do I own the website?", a: "Yes, the website is delivered in your name. You keep ownership of your content and your domain name." },
      { q: "What happens after launch?", a: "I show you how the site works and stay available. If you wish, I can handle updates through the maintenance plan." },
      { q: "Do you only work in Aix-en-Provence?", a: "I'm based in Aix-en-Provence and work with businesses across Provence. Everything can be done remotely, by email." },
    ],
    quoteCardTag: "Recommended",
    quoteCardTitle: "Estimate my website price",
    quoteCardText: "A few questions about your project, with a price estimate at the end. I then email you the detailed quote.",
    quoteCardMeta: ["3 minutes", "No commitment", "Detailed quote by email"],
    quoteCardCta: "Start my request",
    formHeading: "Just a quick message?",
    formDescription: "A few lines are enough. Add your current website if you have one.",
    formName: "Your name",
    formEmail: "Your email",
    formCompany: "Business / activity",
    formWebsite: "Current website (optional)",
    formService: "What do you need?",
    formServicePlaceholder: "Choose a service",
    formServices: ["Website redesign", "Showcase website", "Landing page", "Maintenance"],
    formMessage: "Your project in a few words",
    formSend: "Send my enquiry",
    formSending: "Sending…",
    formSuccess: "Thank you! Your message has been sent. I'll reply personally.",
    formError: "The message could not be sent. You can also email me directly.",
    formPrivacy: "Your information is used only to reply to you.",
    directEmail: "Email me directly",
  },
} as const satisfies Record<Locale, object>;
